<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AITool.Application\AITool.Application.csproj" />
    <ProjectReference Include="..\AITool.Protocol\AITool.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AITool.ApplicationTests" />
    <InternalsVisibleTo Include="AITool.Core.IntegrationTests" />
    <InternalsVisibleTo Include="AITool.Admin.IntegrationTests" />
    <InternalsVisibleTo Include="AITool.Admin" />
    <InternalsVisibleTo Include="AITool.Core" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.17" />
    <PackageReference Include="Hangfire.InMemory" Version="1.0.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.215" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
